spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #This is to discover the service with lower case.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka