spring:
  application:
    name: user
server:
  port: 8082
service:
  url: http://localhost:8080/package/getPackage

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

